dataset:
  path: TODO: set the path to the base data directory (do not use apostrophes)

model:
  model_name: "TODO: set the model name"

training:
  optimizer: "TODO: set the optimizer"
  epochs: 3
  learning_rate: 2e-5
  batch_size: 32
  weight_decay: 0.01
  max_grad_norm: 1.0
  warmup_steps: 0.1
